sonar.projectKey=aignostics_foundry-python-core
sonar.organization=aignostics
sonar.projectVersion=0.1.0
sonar.projectDescription=🏭 Foundational infrastructure for Foundry components.
sonar.links.homepage=https://github.com/aignostics/foundry-python-core
sonar.links.scm=https://github.com/aignostics/foundry-python-core
sonar.links.ci=https://github.com/aignostics/foundry-python-core/actions
sonar.links.issues=https://github.com/aignostics/foundry-python-core/issues
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.version=3.11, 3.12, 3.13
sonar.coverage.exclusions=noxfile.py, template/**, tests/**, docs/**, dist/**
sonar.exclusions=template/**, docs/**, dist/**
