"""Generate reports/ATTRIBUTIONS.md from installed package licenses."""

import json
import subprocess
import sys
import tomllib
from pathlib import Path


def _package_name() -> str:
    """Read the project package name from pyproject.toml.

    Returns:
        str: The package name, or empty string if not found.
    """
    pyproject = Path("pyproject.toml")
    if pyproject.exists():
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        name = data.get("project", {}).get("name", "")
        if name:
            return name
    return ""


def _format_package_attribution(pkg: dict[str, str]) -> str:
    """Format attribution text for a single package.

    Args:
        pkg: Package metadata dictionary from pip-licenses.

    Returns:
        str: Formatted Markdown attribution block for the package.
    """
    name = pkg.get("Name", "Unknown")
    version = pkg.get("Version", "Unknown")
    license_name = pkg.get("License", "Unknown")
    authors = pkg.get("Author", "Unknown")
    maintainers = pkg.get("Maintainer", "")
    url = pkg.get("URL", "")
    description = pkg.get("Description", "")

    attribution = f"## {name} ({version}) - {license_name}\n\n"

    if description:
        attribution += f"{description}\n\n"
    if url:
        attribution += f"* URL: {url}\n"
    if authors and authors != "UNKNOWN":
        attribution += f"* Author(s): {authors}\n"
    if maintainers and maintainers != "UNKNOWN":
        attribution += f"* Maintainer(s): {maintainers}\n"
    attribution += "\n"

    license_text = pkg.get("LicenseText", "")
    if license_text and license_text != "UNKNOWN":
        attribution += "### License Text\n\n"
        attribution += f"```\n{license_text.replace('```', '~~~')}\n```\n\n"

    notice_text = pkg.get("NoticeText", "")
    if notice_text and notice_text != "UNKNOWN":
        attribution += "### Notice\n\n"
        attribution += f"```\n{notice_text.replace('```', '~~~')}\n```\n\n"

    return attribution


def main() -> None:
    """Generate reports/ATTRIBUTIONS.md from pip-licenses output."""
    package_name = _package_name()
    cmd = [
        "pip-licenses",
        "--with-system",
        "--with-authors",
        "--with-maintainer",
        "--with-url",
        "--with-description",
        "--with-license-file",
        "--with-notice-file",
        "--format=json",
    ]
    if package_name:
        cmd += ["--ignore-packages", package_name]

    result = subprocess.run(cmd, capture_output=True, text=True, check=False)  # noqa: S603
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)

    licenses_data: list[dict[str, str]] = json.loads(result.stdout or "[]")

    content = "# Attributions\n\n"
    content += "[//]: # (This file is generated by mise run attributions)\n\n"
    content += "This project includes code from the following third-party open source projects:\n\n"
    for pkg in licenses_data:
        content += _format_package_attribution(pkg)
    content = content.rstrip() + "\n"

    Path("reports").mkdir(exist_ok=True)
    Path("reports/ATTRIBUTIONS.md").write_text(content, encoding="utf-8")
    print("Generated reports/ATTRIBUTIONS.md")


if __name__ == "__main__":
    main()
